# Generated by Django 4.2.7 on 2023-12-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_groups_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group_type',
            field=models.CharField(choices=[('Parent', 'Parent'), ('Child', 'Child')], default='Parent', max_length=10),
        ),
    ]
